using System.Text;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.DependencyInjection;

namespace ConsoleApp1;

public sealed record DbContextSource(string ServiceName, DbContext Context)
{
    /// <summary>
    /// The full design-time model for this context. Includes comments,
    /// annotations, and other metadata stripped from the runtime model.
    /// </summary>
    public IModel Model => Context.GetService<IDesignTimeModel>().Model;
}
/// <summary>
/// Generates DBML (https://dbml.dbdiagram.io) from one or more EF Core DbContext
/// instances. Each DbContext is treated as a bounded context belonging to a
/// separate service, and its entities are grouped together via TableGroup.
///
/// Intra-service foreign keys declared in the EF model are emitted as solid
/// Ref lines. Cross-service references — which have no FK constraint at the
/// database level in a microservices architecture — are detected via naming
/// convention (e.g. EventId, UserId) and emitted as annotated soft Refs.
/// </summary>
public sealed class DbmlGenerator
{
    private readonly string _projectName;
    private readonly string _databaseType;
    private readonly string _projectNote;
 
    // Stable, high-contrast color palette for TableGroup headers.
    // Assigned to services in registration order.
    private static readonly string[] ServiceColors =
    [
        "#2563EB", // blue
        "#16A34A", // green
        "#DC2626", // red
        "#9333EA", // purple
        "#EA580C", // orange
        "#0891B2", // cyan
        "#CA8A04", // amber
    ];
 
    public DbmlGenerator(string projectName, string databaseType, string projectNote)
    {
        _projectName = projectName;
        _databaseType = databaseType;
        _projectNote = projectNote;
    }
 
    public string Generate(IReadOnlyList<DbContextSource> services)
    {
        var globalIndex = BuildGlobalEntityIndex(services);
        var sb = new StringBuilder();
 
        WriteHeader(sb);
        WriteEnums(sb, services);
 
        for (var i = 0; i < services.Count; i++)
        {
            var svc = services[i];
            var color = ServiceColors[i % ServiceColors.Length];
            WriteServiceTables(sb, svc, color);
        }
 
        WriteIntraServiceRefs(sb, services);
        WriteCrossServiceRefs(sb, services, globalIndex);
        WriteTableGroups(sb, services);
 
        return sb.ToString();
    }
 
    // ─────────────────────────────────────────────────────────────────────────
    // Header
    // ─────────────────────────────────────────────────────────────────────────
 
    private void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine($"// Auto-generated by Hostlistic.SchemaDiagramGenerator");
        sb.AppendLine($"// Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"// Paste this file at https://dbdiagram.io to render.");
        sb.AppendLine();
        sb.AppendLine($"Project {_projectName} {{");
        sb.AppendLine($"  database_type: '{_databaseType}'");
        sb.AppendLine($"}}");
        sb.AppendLine();
    }
 
    // ─────────────────────────────────────────────────────────────────────────
    // Enums — collected across all services, deduplicated by full type name
    // ─────────────────────────────────────────────────────────────────────────
 
    private static void WriteEnums(StringBuilder sb, IReadOnlyList<DbContextSource> services)
    {
        var enumTypes = services
            .SelectMany(s => s.Model.GetEntityTypes())
            .SelectMany(e => e.GetProperties())
            .Select(p => Nullable.GetUnderlyingType(p.ClrType) ?? p.ClrType)
            .Where(t => t.IsEnum)
            .DistinctBy(t => t.FullName)
            .OrderBy(t => t.Name)
            .ToList();
 
        if (enumTypes.Count == 0) return;
 
        sb.AppendLine("// ─────────────────────────── Enums ───────────────────────────");
        sb.AppendLine();
 
        foreach (var enumType in enumTypes)
        {
            sb.AppendLine($"Enum {ToDbmlIdentifier(enumType.Name)} {{");
            foreach (var name in Enum.GetNames(enumType))
            {
                sb.AppendLine($"  {ToDbmlIdentifier(name)}");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }
 
    // ─────────────────────────────────────────────────────────────────────────
    // Tables
    // ─────────────────────────────────────────────────────────────────────────
 
    private static void WriteServiceTables(
        StringBuilder sb, DbContextSource svc, string headerColor)
    {
        sb.AppendLine($"// ─────────────────────── {svc.ServiceName} ───────────────────────");
        sb.AppendLine();
 
        var entities = svc.Model
            .GetEntityTypes()
            .Where(e => !e.IsOwned())
            .OrderBy(e => e.GetTableName() ?? e.ClrType.Name)
            .ToList();
 
        foreach (var entity in entities)
        {
            WriteTable(sb, entity, headerColor);
            sb.AppendLine();
        }
    }
 
    private static void WriteTable(StringBuilder sb, IEntityType entity, string headerColor)
    {
        var tableName = entity.GetTableName() ?? entity.ClrType.Name;
        var schema = entity.GetSchema();
        var qualifiedName = schema is null ? tableName : $"{schema}.{tableName}";
 
        var comment = entity.GetComment();
        var headerParts = new List<string> { $"headercolor: {headerColor}" };
 
        sb.AppendLine($"Table {qualifiedName} [{string.Join(", ", headerParts)}] {{");
 
        var primaryKey = entity.FindPrimaryKey();
        var pkColumns = primaryKey?.Properties.Select(p => p.GetColumnName()).ToHashSet()
                        ?? new HashSet<string>();
 
        // Single-column PKs are marked inline via [pk]. Composite PKs need an
        // indexes block because DBML only supports inline [pk] for single cols.
        var isCompositePk = pkColumns.Count > 1;
 
        foreach (var property in entity.GetProperties())
        {
            WriteColumn(sb, property, pkColumns, isCompositePk);
        }
 
        WriteTableIndexes(sb, entity, isCompositePk, pkColumns);
 
        sb.AppendLine("}");
    }
 
    private static void WriteColumn(
        StringBuilder sb, IProperty property, HashSet<string> pkColumns, bool isCompositePk)
    {
        var columnName = property.GetColumnName();
        var dbmlType = TypeMapper.Map(property);
 
        var attributes = new List<string>();
 
        if (!isCompositePk && pkColumns.Contains(columnName))
            attributes.Add("pk");
 
        if (!property.IsNullable)
            attributes.Add("not null");
 
        if (property.IsUniqueIndex())
            attributes.Add("unique");
 
        var defaultSql = property.GetDefaultValueSql();
        if (!string.IsNullOrWhiteSpace(defaultSql))
            attributes.Add($"default: `{defaultSql}`");
        else if (property.GetDefaultValue() is { } defaultValue)
            attributes.Add($"default: {FormatDefaultValue(defaultValue)}");
 
        if (property.ValueGenerated == ValueGenerated.OnAdd
            && string.IsNullOrWhiteSpace(defaultSql)
            && property.GetDefaultValue() is null
            && !attributes.Contains("pk"))
        {
            // EF-managed identity / generated value — annotate for clarity.
            attributes.Add("increment");
        }
        
        var attrString = attributes.Count > 0
            ? $" [{string.Join(", ", attributes)}]"
            : string.Empty;
 
        sb.AppendLine($"  {columnName} {dbmlType}{attrString}");
    }
 
    private static void WriteTableIndexes(
        StringBuilder sb, IEntityType entity, bool isCompositePk, HashSet<string> pkColumns)
    {
        var indexes = entity.GetIndexes().ToList();
 
        if (!isCompositePk && indexes.Count == 0) return;
 
        sb.AppendLine();
        sb.AppendLine("  indexes {");
 
        if (isCompositePk)
        {
            var pkCols = string.Join(", ", pkColumns);
            sb.AppendLine($"    ({pkCols}) [pk]");
        }
 
        foreach (var index in indexes)
        {
            var cols = string.Join(", ",
                index.Properties.Select(p => p.GetColumnName()));
 
            var attrs = new List<string>();
            if (index.IsUnique) attrs.Add("unique");
 
            var indexName = index.GetDatabaseName();
            if (!string.IsNullOrWhiteSpace(indexName))
                attrs.Add($"name: '{indexName}'");
 
            var attrString = attrs.Count > 0
                ? $" [{string.Join(", ", attrs)}]"
                : string.Empty;
 
            sb.AppendLine($"    ({cols}){attrString}");
        }
 
        sb.AppendLine("  }");
    }
 
    // ─────────────────────────────────────────────────────────────────────────
    // Intra-service Refs (real FKs declared in the EF model)
    // ─────────────────────────────────────────────────────────────────────────
 
    private static void WriteIntraServiceRefs(
        StringBuilder sb, IReadOnlyList<DbContextSource> services)
    {
        sb.AppendLine("// ─────────────────── Intra-service Foreign Keys ───────────────────");
        sb.AppendLine();
 
        foreach (var svc in services)
        {
            var entities = svc.Model.GetEntityTypes();
            foreach (var entity in entities)
            {
                foreach (var fk in entity.GetForeignKeys())
                {
                    WriteForeignKey(sb, fk);
                }
            }
        }
        sb.AppendLine();
    }
 
    private static void WriteForeignKey(StringBuilder sb, IForeignKey fk)
    {
        var dependentTable = fk.DeclaringEntityType.GetTableName();
        var principalTable = fk.PrincipalEntityType.GetTableName();
 
        if (dependentTable is null || principalTable is null) return;
 
        var dependentCols = string.Join(", ", fk.Properties.Select(p => p.GetColumnName()));
        var principalCols = string.Join(", ",
            fk.PrincipalKey.Properties.Select(p => p.GetColumnName()));
 
        // "<" in DBML means many-to-one from left to right; we express the FK
        // with ">" which is dependent (many) -> principal (one).
        var attrs = new List<string>();
        var deleteAction = MapDeleteBehavior(fk.DeleteBehavior);
        if (deleteAction is not null) attrs.Add($"delete: {deleteAction}");
 
        var attrString = attrs.Count > 0
            ? $" [{string.Join(", ", attrs)}]"
            : string.Empty;
 
        // Single-column FK uses the simple form; composite FK uses parenthesized form.
        var left = fk.Properties.Count == 1
            ? $"{dependentTable}.{dependentCols}"
            : $"{dependentTable}.({dependentCols})";
 
        var right = fk.PrincipalKey.Properties.Count == 1
            ? $"{principalTable}.{principalCols}"
            : $"{principalTable}.({principalCols})";
 
        sb.AppendLine($"Ref: {left} > {right}{attrString}");
    }
 
    // ─────────────────────────────────────────────────────────────────────────
    // Cross-service soft refs (no real FK — detected by naming convention)
    // ─────────────────────────────────────────────────────────────────────────
 
    private static void WriteCrossServiceRefs(
        StringBuilder sb,
        IReadOnlyList<DbContextSource> services,
        Dictionary<string, EntityLocation> globalIndex)
    {
        var softRefs = new List<string>();
 
        foreach (var svc in services)
        {
            foreach (var entity in svc.Model.GetEntityTypes())
            {
                if (entity.IsOwned()) continue;
 
                var dependentTable = entity.GetTableName();
                if (dependentTable is null) continue;
 
                // Columns already participating in a real FK should be skipped.
                var realFkColumns = entity.GetForeignKeys()
                    .SelectMany(fk => fk.Properties.Select(p => p.GetColumnName()))
                    .ToHashSet();
 
                foreach (var property in entity.GetProperties())
                {
                    var columnName = property.GetColumnName();
                    if (realFkColumns.Contains(columnName)) continue;
 
                    var referencedEntityName = ExtractReferencedEntityName(property.Name);
                    if (referencedEntityName is null) continue;
 
                    if (!globalIndex.TryGetValue(referencedEntityName, out var location))
                        continue;
 
                    // Only emit as soft ref if the target lives in a DIFFERENT service.
                    if (location.ServiceName == svc.ServiceName) continue;
                    
                }
            }
        }
 
        if (softRefs.Count == 0) return;
 
        sb.AppendLine("// ─────────────── Cross-service Soft References ───────────────");
        sb.AppendLine("// These are ID-only references between bounded contexts.");
        sb.AppendLine("// No FK constraint exists at the database level.");
        sb.AppendLine();
 
        foreach (var line in softRefs.Distinct().OrderBy(l => l))
            sb.AppendLine(line);
 
        sb.AppendLine();
    }
 
    /// <summary>
    /// Extracts the referenced entity name from a navigation property name.
    /// Example: "EventId" -> "Event", "OrganizerUserId" -> "OrganizerUser".
    /// Returns null if the property doesn't follow the convention.
    /// </summary>
    private static string? ExtractReferencedEntityName(string propertyName)
    {
        if (!propertyName.EndsWith("Id", StringComparison.Ordinal)) return null;
        if (propertyName.Length <= 2) return null; // "Id" alone — primary key, not a ref.
 
        var candidate = propertyName[..^2];
        return candidate.Length == 0 ? null : candidate;
    }
 
    // ─────────────────────────────────────────────────────────────────────────
    // TableGroup per service — gives visual bounding boxes in dbdiagram.io
    // ─────────────────────────────────────────────────────────────────────────
 
    private static void WriteTableGroups(
        StringBuilder sb, IReadOnlyList<DbContextSource> services)
    {
        sb.AppendLine("// ─────────────────────── Service Boundaries ───────────────────────");
        sb.AppendLine();
 
        foreach (var svc in services)
        {
            var tables = svc.Model
                .GetEntityTypes()
                .Where(e => !e.IsOwned())
                .Select(e => e.GetTableName())
                .Where(t => t is not null)
                .Distinct()
                .OrderBy(t => t)
                .ToList();
 
            if (tables.Count == 0) continue;
 
            sb.AppendLine($"TableGroup {ToDbmlIdentifier(svc.ServiceName)} {{");
            foreach (var table in tables)
                sb.AppendLine($"  {table}");
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }
 
    // ─────────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────────
 
    private static Dictionary<string, EntityLocation> BuildGlobalEntityIndex(
        IReadOnlyList<DbContextSource> services)
    {
        // Maps CLR entity name (e.g. "Event") to the (serviceName, tableName)
        // in which it is declared. Used to detect cross-service soft references.
        var index = new Dictionary<string, EntityLocation>(StringComparer.Ordinal);
 
        foreach (var svc in services)
        {
            foreach (var entity in svc.Model.GetEntityTypes())
            {
                if (entity.IsOwned()) continue;
 
                var tableName = entity.GetTableName();
                if (tableName is null) continue;
 
                // Last-registered wins if a name collision exists — deliberate,
                // since registration order reflects dependency order in practice.
                index[entity.ClrType.Name] = new EntityLocation(svc.ServiceName, tableName);
            }
        }
 
        return index;
    }
 
    private static string? MapDeleteBehavior(DeleteBehavior behavior) => behavior switch
    {
        DeleteBehavior.Cascade => "cascade",
        DeleteBehavior.SetNull => "set null",
        DeleteBehavior.Restrict => "restrict",
        DeleteBehavior.NoAction => "no action",
        _ => null,
    };
 
    private static string FormatDefaultValue(object value) => value switch
    {
        bool b => b ? "`true`" : "`false`",
        string s => $"'{EscapeSingleQuote(s)}'",
        _ => $"`{value}`",
    };
 
    private static string EscapeSingleQuote(string value) =>
        value.Replace("'", "\\'");
 
    private static string ToDbmlIdentifier(string value) =>
        Regex.Replace(value, "[^A-Za-z0-9_]", "_");
 
    private sealed record EntityLocation(string ServiceName, string TableName);
}
 
/// <summary>
/// Maps a CLR property to its DBML type representation.
/// Falls back to the configured store type name when a specific CLR mapping
/// is unavailable, preserving PostgreSQL-specific types like jsonb and uuid.
/// </summary>
internal static class TypeMapper
{
    public static string Map(IProperty property)
    {
        // Prefer the explicit column type when the developer has set one
        // (e.g. via HasColumnType("jsonb") or [Column(TypeName = ...)]).
        var configuredType = property.GetColumnType();
        if (!string.IsNullOrWhiteSpace(configuredType))
            return NormalizeColumnType(configuredType, property);
 
        var clrType = Nullable.GetUnderlyingType(property.ClrType) ?? property.ClrType;
 
        if (clrType.IsEnum) return clrType.Name;
 
        return clrType.Name switch
        {
            nameof(Guid) => "uuid",
            nameof(String) => FormatString(property),
            nameof(Int16) => "smallint",
            nameof(Int32) => "integer",
            nameof(Int64) => "bigint",
            nameof(Boolean) => "boolean",
            nameof(Decimal) => "numeric",
            nameof(Double) => "double_precision",
            nameof(Single) => "real",
            nameof(DateTime) => "timestamptz",
            nameof(DateTimeOffset) => "timestamptz",
            nameof(DateOnly) => "date",
            nameof(TimeOnly) => "time",
            nameof(TimeSpan) => "interval",
            "Byte[]" => "bytea",
            _ => "text",
        };
    }
 
    private static string NormalizeColumnType(string columnType, IProperty property)
    {
        // DBML doesn't understand spaces in type names, so replace with
        // underscores to keep the type parseable while preserving semantics.
        var lower = columnType.Trim().ToLowerInvariant();
        return lower switch
        {
            "double precision" => "double_precision",
            "character varying" => FormatString(property),
            _ => lower.Replace(' ', '_'),
        };
    }
 
    private static string FormatString(IProperty property)
    {
        var maxLength = property.GetMaxLength();
        return maxLength.HasValue ? $"varchar({maxLength})" : "text";
    }
}
/// <summary>
/// Convenience extensions for working with EF Core metadata.
/// </summary>
internal static class MetadataExtensions
{
    /// <summary>
    /// Returns true if this property is the sole column of a unique index.
    /// Used to flag columns inline with [unique] rather than in an index block.
    /// </summary>
    public static bool IsUniqueIndex(this IProperty property)
    {
        if (property.DeclaringType is not IEntityType entityType)
            return false;
 
        return entityType
            .GetIndexes()
            .Any(ix => ix.IsUnique
                       && ix.Properties.Count == 1
                       && ix.Properties[0] == property);
    }
}